-- ============================================================================
-- 001 — viewings
--
-- Run this ONCE in the Supabase SQL Editor before deploying the viewings feature.
--
-- Written by hand rather than generated by drizzle-kit. drizzle.config.ts points at
-- ./lib/db/migrations, which does not exist: the live schema was applied by other
-- means, so `drizzle-kit generate` would produce a fresh baseline containing every
-- existing table and `drizzle-kit migrate` would then fail trying to create tables
-- that are already there. One hand-written file is safer and easier to read.
--
-- Safe to run twice: every statement is IF NOT EXISTS.
-- ============================================================================

CREATE TABLE IF NOT EXISTS viewings (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  property_id   uuid NOT NULL REFERENCES properties(id) ON DELETE CASCADE,

  -- Exactly one of contact_id / lead_id is set. Agents show properties to people who
  -- have not been qualified yet, so a viewing must be able to hang off a lead.
  contact_id    uuid REFERENCES contacts(id) ON DELETE CASCADE,
  lead_id       uuid REFERENCES leads(id)    ON DELETE CASCADE,

  assigned_to   uuid REFERENCES users(id) ON DELETE SET NULL,

  scheduled_at  timestamptz NOT NULL,

  -- scheduled | completed | no-show | cancelled
  status        varchar(20) NOT NULL DEFAULT 'scheduled',

  -- Recorded afterwards: interested | not-interested | offer-made | undecided
  outcome       varchar(20),

  notes         text,

  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  deleted_at    timestamptz,

  -- Enforce "exactly one client" in the database, not just in application code.
  -- Application checks are bypassed by imports, scripts and future code paths;
  -- a constraint is not.
  CONSTRAINT viewings_one_client CHECK (
    (contact_id IS NOT NULL AND lead_id IS NULL) OR
    (contact_id IS NULL AND lead_id IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS viewings_property_idx ON viewings (property_id);
CREATE INDEX IF NOT EXISTS viewings_contact_idx  ON viewings (contact_id);
CREATE INDEX IF NOT EXISTS viewings_lead_idx     ON viewings (lead_id);
CREATE INDEX IF NOT EXISTS viewings_assigned_idx ON viewings (assigned_to);

-- Every list query is "upcoming, soonest first, excluding deleted", so the partial
-- index serves the filter and the sort together.
CREATE INDEX IF NOT EXISTS viewings_scheduled_idx
  ON viewings (scheduled_at)
  WHERE deleted_at IS NULL;

-- Verify:
--   SELECT column_name, data_type FROM information_schema.columns
--   WHERE table_name = 'viewings' ORDER BY ordinal_position;
